on:
  push:
    tags:
      - v*.*.*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Pack:    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pack with dotnet
      run: dotnet pack --configuration Release --output output
    - name: Publish NuGet
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${NUGET_API_KEY} --skip-duplicate ./output/*.nupkg
      env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}